default_language_version:
  python: python3.11.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-yaml
      - id: check-docstring-first
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: ["--extend-ignore=E203,E402,E501"]
      exclude: etf_service_pb2*

  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
      exclude: etf_service_pb2*
