services:
  news_service:
    container_name: news_service_python
    build:
      context: ./news-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - database

  redis:
    container_name: redis_cache_service
    image: redis:7.2.4-alpine3.19

  database:
    container_name: asset_mate_db
    image: postgres:16.3-alpine3.19
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  api_server:
    build:
      context: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/bartoszpiechnik/volume/postgres'
