# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etf_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x65tf_service.proto"L\n\x0b\x45tfHoldings\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x14\n\x0cholding_name\x18\x02 \x01(\t\x12\x17\n\x0fholding_percent\x18\x03 \x01(\x02";\n\rSectorWeights\x12\x13\n\x0bsector_name\x18\x01 \x01(\t\x12\x15\n\rsector_weight\x18\x02 \x01(\x02"\xbd\x01\n\x03\x45tf\x12\x14\n\x0cyahoo_symbol\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x1e\n\x08holdings\x18\x04 \x03(\x0b\x32\x0c.EtfHoldings\x12\x1f\n\x07weights\x18\x05 \x03(\x0b\x32\x0e.SectorWeights\x12\x14\n\x0ctotal_assets\x18\x06 \x01(\x03\x12\x15\n\rexpense_ratio\x18\x07 \x01(\x02\x12\x12\n\nlast_close\x18\x08 \x01(\x02"\x1c\n\x0cGetEtfByName\x12\x0c\n\x04name\x18\x01 \x01(\t"#\n\x0b\x45tfByTicker\x12\x14\n\x0cyahoo_symbol\x18\x01 \x01(\t2L\n\nEtfService\x12\x1e\n\x06GetEtf\x12\x0c.EtfByTicker\x1a\x04.Etf"\x00\x12\x1e\n\x06\x41\x64\x64\x45tf\x12\x0c.EtfByTicker\x1a\x04.Etf"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "etf_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_ETFHOLDINGS"]._serialized_start = 21
    _globals["_ETFHOLDINGS"]._serialized_end = 97
    _globals["_SECTORWEIGHTS"]._serialized_start = 99
    _globals["_SECTORWEIGHTS"]._serialized_end = 158
    _globals["_ETF"]._serialized_start = 161
    _globals["_ETF"]._serialized_end = 350
    _globals["_GETETFBYNAME"]._serialized_start = 352
    _globals["_GETETFBYNAME"]._serialized_end = 380
    _globals["_ETFBYTICKER"]._serialized_start = 382
    _globals["_ETFBYTICKER"]._serialized_end = 417
    _globals["_ETFSERVICE"]._serialized_start = 419
    _globals["_ETFSERVICE"]._serialized_end = 495
# @@protoc_insertion_point(module_scope)
